# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keven Imbeault | Blog
email: xkeke111x@gmail.com
description: Le blog officiel de Keven Imbeault - kevenimbeault.github.io
baseurl: "/Blog" # the subpath of your site, e.g. /blog
url: "https://kevenimbeault.github.io" # the base hostname & protocol for your site
twitter_username: xKeke111x
github_username:  KevenImbeault

# Build settings
markdown: kramdown
